name: 'Upload Zip to Cloud Storage'

on:
  push:
    branches:
      - main

jobs:
    upload-zip:
        runs-on: ubuntu-latest

        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
        - name: Checkout Repository
          uses: 'actions/checkout@v4'

        - name: Zip the current directory
          run: zip -r /tmp/test-v1.zip . && ls -l /tmp

        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
            service_account: ${{ secrets.SERVICE_ACCOUNT }}

        - id: 'upload-file'
          uses: 'google-github-actions/upload-cloud-storage@v2'
          with:
            path: '/tmp/test-v1.zip'
            destination: 'test-file'
